spring:
  application:
    name: MysqlApi
  datasource:
    url: jdbc:mysql://localhost:3306/second_hand_trading?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081
mybatis:
  type-aliases-package:
    - com.MysqlApi.Login.Dao
    - com.MysqlApi.Register.Dao
    - com.MysqlApi.AllUserManage.Dao
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql